# Generated by Django 4.1 on 2022-11-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=25, verbose_name='Группа')),
                ('UUID', models.IntegerField(verbose_name='UUID')),
                ('type', models.CharField(max_length=36, verbose_name='Тип')),
                ('cod', models.CharField(max_length=36, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('discription', models.TextField(max_length=200, verbose_name='Описание')),
                ('out_cod', models.CharField(max_length=36, verbose_name='Внешний код')),
                ('article', models.CharField(max_length=36, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('valut', models.CharField(max_length=36, verbose_name='Валюта')),
                ('in_price', models.IntegerField(verbose_name='Закупоная цена')),
                ('valut_in_price', models.CharField(max_length=36, verbose_name='Валюта Закупоной цены')),
                ('shtrih', models.IntegerField(verbose_name='Штрих код ')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
