# Generated by Django 4.1 on 2022-11-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='valut',
            field=models.CharField(max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='valut_in_price',
            field=models.CharField(max_length=3, verbose_name='Валюта Закупоной цены'),
        ),
    ]
